# Generated by Django 4.2.27 on 2026-01-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeituraScada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "xid",
                    models.CharField(
                        max_length=100, verbose_name="Identificador do Ponto"
                    ),
                ),
                ("eixo_x", models.FloatField(verbose_name="Eixo X")),
                ("eixo_y", models.FloatField(verbose_name="Eixo Y")),
                ("data_leitura", models.DateTimeField(verbose_name="Data da Leitura")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Leitura Scada",
                "verbose_name_plural": "Leituras Scada",
                "ordering": ["-data_leitura"],
            },
        ),
    ]
