# Generated by Django 4.2.27 on 2026-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leiturascada",
            options={
                "ordering": ["data_leitura"],
                "verbose_name": "Leitura Scada",
                "verbose_name_plural": "Leituras Scada",
            },
        ),
        migrations.AddField(
            model_name="leiturascada",
            name="scan_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="ID do Ciclo",
            ),
        ),
        migrations.AlterField(
            model_name="leiturascada",
            name="eixo_x",
            field=models.FloatField(verbose_name="Largura (X)"),
        ),
        migrations.AlterField(
            model_name="leiturascada",
            name="eixo_y",
            field=models.FloatField(verbose_name="Espessura (Y)"),
        ),
    ]
