# Generated by Django 6.1.1 on 2026-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_leiturascada_options_leiturascada_scan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadaDataPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('xid', models.CharField(max_length=50, unique=True)),
                ('data_source_id', models.IntegerField(db_column='dataSourceId')),
                ('point_name', models.CharField(blank=True, db_column='pointName', max_length=250, null=True)),
                ('plc_alarm_level', models.IntegerField(blank=True, db_column='plcAlarmLevel', null=True)),
            ],
            options={
                'verbose_name': 'Data Point (Scada-LTS)',
                'verbose_name_plural': 'Data Points (Scada-LTS)',
                'db_table': 'datapoints',
                'ordering': ['xid'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScadaPointValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_point_id', models.IntegerField(db_column='dataPointId', db_index=True)),
                ('data_type', models.IntegerField(db_column='dataType')),
                ('point_value', models.FloatField(blank=True, db_column='pointValue', null=True)),
                ('ts', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Point Value (Scada-LTS)',
                'verbose_name_plural': 'Point Values (Scada-LTS)',
                'db_table': 'pointvalues',
                'ordering': ['-ts', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScadaPointValueAnnotation',
            fields=[
                ('point_value_id', models.BigIntegerField(db_column='pointValueId', primary_key=True, serialize=False)),
                ('text_short', models.CharField(blank=True, db_column='textPointValueShort', max_length=128, null=True)),
                ('text_long', models.TextField(blank=True, db_column='textPointValueLong', null=True)),
            ],
            options={
                'verbose_name': 'Point Value Annotation (Scada-LTS)',
                'verbose_name_plural': 'Point Value Annotations (Scada-LTS)',
                'db_table': 'pointvalueannotations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('mysql', 'MySQL Direto (Somente Leitura)'), ('rest_api', 'API REST HTTP Legada (Fallback)')], default='rest_api', help_text='Define se a leitura é realizada diretamente no banco MySQL ou via API REST HTTP.', max_length=20, verbose_name='Origem de Aquisição')),
                ('xid_gatilho', models.CharField(default='DP_887366', help_text='Tag booleana que detecta presença de chapa (início/fim de varredura).', max_length=50, verbose_name='XID do Gatilho')),
                ('xid_medicao', models.CharField(default='DP_747174', help_text="Tag alfanumérica/JSON com coordenadas de espessura [{'x': ..., 'y': ...}].", max_length=50, verbose_name='XID da Medição Dimensional')),
                ('aquisicao_ativa', models.BooleanField(default=True, help_text='Habilita ou pausa temporariamente a coleta de novos dados sem parar o servidor.', verbose_name='Aquisição Ativa')),
                ('intervalo_consulta', models.FloatField(default=0.05, help_text='Tempo de espera entre polls (ex: 0.05 = 50ms, 0.20 = 200ms).', verbose_name='Intervalo de Consulta (s)')),
                ('limite_stale_segundos', models.IntegerField(default=30, help_text='Tempo máximo antes de classificar um dado como STALE.', verbose_name='Limite de Amostra Obsoleta (s)')),
                ('delta_x_minimo', models.FloatField(default=0.1, help_text='Filtro de deslocamento espacial: descarta gravações repetidas quando o sensor estiver parado.', verbose_name='Delta X Mínimo (mm)')),
                ('tamanho_lote_incremental', models.IntegerField(default=500, help_text='Quantidade máxima de medições obtidas por ciclo no modo MySQL.', verbose_name='Tamanho de Lote Incremental')),
                ('espessura_borda_nominal', models.FloatField(default=2.0, help_text='Espessura de referência para a região de borda da chapa.', verbose_name='Espessura Nominal de Borda (mm)')),
                ('espessura_centro_nominal', models.FloatField(default=10.0, help_text='Espessura de referência para a região central da chapa.', verbose_name='Espessura Nominal de Centro (mm)')),
                ('tolerancia_positiva', models.FloatField(default=0.5, help_text='Variação máxima aceitável acima do valor nominal (limite superior = nominal + tol).', verbose_name='Tolerância Superior (+) (mm)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
    ]
