"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis do arquivo .env
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-&yivy06du01_qs944zlhiagv$k2d+$soisy!suba&*m3p+y0mq"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'core',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "scada": {
        "ENGINE": os.environ.get("SCADA_DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.environ.get("SCADA_DB_NAME", "scadalts"),
        "USER": os.environ.get("SCADA_DB_USER", "scada_monitor_ro"),
        "PASSWORD": os.environ.get("SCADA_DB_PASSWORD", ""),
        "HOST": os.environ.get("SCADA_DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("SCADA_DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "connect_timeout": int(os.environ.get("SCADA_DB_CONNECT_TIMEOUT", "5")),
        },
    },
}

# Roteador de Banco de Dados Multi-DB (Segurança estrita de somente-leitura e bloqueio de migrações)
DATABASE_ROUTERS = ["core.routers.ScadaRouter"]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Configurações de Integração Scada-LTS ────────────────────────────────────
SCADA_DATA_SOURCE = os.environ.get("SCADA_DATA_SOURCE", "rest_api").lower()
SCADA_REST_BASE_URL = os.environ.get("SCADA_REST_BASE_URL", "http://192.168.0.202:8080/Scada-LTS")
SCADA_REST_USERNAME = os.environ.get("SCADA_REST_USERNAME", "teste")
SCADA_REST_PASSWORD = os.environ.get("SCADA_REST_PASSWORD", "teste1")
SCADA_XID_GATILHO = os.environ.get("SCADA_XID_GATILHO", "DP_887366")
SCADA_XID_MEDICAO = os.environ.get("SCADA_XID_MEDICAO", "DP_747174")
SCADA_AUTO_WORKER = os.environ.get("SCADA_AUTO_WORKER", "False").lower() in ("true", "1", "yes")

